spring:
  application:
    name: "zuul-server"

server:
  port: 8080

zuul:
  routes:
    comments-service: /comments/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/